use MER5;
SELECT CLIENT.nom, VEHICLE.marca_fabricant, TIPUS_VEHICLE.nom, CITA.data_cita, CITA.lloc, CLIENT_VEHICLE.data_darrera_revisio
FROM CLIENT, VEHICLE, TIPUS_VEHICLE, CITA, CLIENT_VEHICLE
WHERE CLIENT.DNI=CLIENT_VEHICLE.CLIENT_DNI and
	VEHICLE.num_bastidor=CLIENT_VEHICLE.VEHICLE_num_bastidor and
    TIPUS_VEHICLE.ID=TIPUS_VEHICLE_ID and
    CLIENT_VEHICLE.ID=CITA.CLIENT_VEHICLE_ID;