use MER4;
SELECT CLIENT.nom, CLIENT.cognoms, VENEDOR.nom, VENEDOR.cognoms, POLISSA.num_polissa, TIPUS_POLISSA.nom
FROM CLIENT, VENEDOR, POLISSA, TIPUS_POLISSA
WHERE CLIENT.DNI = POLISSA.CLIENT_DNI and VENEDOR.DNI=POLISSA.VENEDOR_DNI and POLISSA.TIPUS_POLISSA_ID and TIPUS_POLISSA.ID;